/* Generated by scripts/build-en-articles-data.mjs. */
window.EN_ARTICLES = [
  {
    "slug": "three-levels-of-cross-review",
    "title": "How Do You Design Mutual Review Between Two AIs?: Three Levels of Review Mechanism",
    "summary": "Asking a second AI to catch your mistakes comes in three depths: review the output only, run two independent tracks and merge, or run a full dual-track mutual review. Most people only know the first, and the first is exactly the one that cannot catch the most expensive kind of error. This article gives copy-ready prompts for each level, the criteria for choosing, the cost, stop conditions, what to do when the other model is unreachable, and a fallback when you only have one vendor.",
    "date": "2026-08-06",
    "url": "articles/three-levels-of-cross-review/"
  },
  {
    "slug": "after-ai-says-remembered",
    "title": "Why Does the AI Keep Forgetting What I Told It?: From \"I&#x27;ll Remember That\" to Letting It Run Itself",
    "summary": "The AI says it will remember, and next time it goes back to the old way. \"Remember\" has three meanings: remembered inside this chat window, written to a file that never gets read, or saved as a rule whose trigger phrase was never set properly. Collected from a live talk on 2026-08-02: seven follow-up questions, a copy-ready checklist, three depths of mutual review, and the four rules I always write into a loop.",
    "date": "2026-08-06",
    "url": "articles/after-ai-says-remembered/"
  },
  {
    "slug": "mobile-to-desktop-publish-loop",
    "title": "Can I Get the Computer at Home Started While I Am Out?: One QR Code Scan and the Desktop Begins",
    "summary": "I hear something good while out, send a link and one voice note from my phone, and the computer at home starts analysing it, drafts a short post in my own voice, makes the image cards, and publishes. This article gives the four setup steps (open settings, go to Connections, allow connections, press Add for a QR code and scan it), the five stages of the loop, which gate must stay human, four image checks you can copy directly, and the two gaps this run exposed.",
    "date": "2026-08-05",
    "url": "articles/mobile-to-desktop-publish-loop/"
  },
  {
    "slug": "long-document-review-layers",
    "title": "The AI Revised It Ten Times and It Is Still Wrong. Now What?: Cleaning the Data Is Only the First Layer",
    "summary": "One 150-page training deck, one model that revised it a dozen times and found nothing, another model that immediately caught a standards error. Long documents usually fail because three layers of design are missing: material, slicing, and perspective. This article opens up each layer, including a rule that pins the standard and version, two slicing methods that cover each other&#x27;s blind spots, and a fallback for when you only have one vendor.",
    "date": "2026-08-05",
    "url": "articles/long-document-review-layers/"
  },
  {
    "slug": "before-installing-others-skill",
    "title": "Will Someone Else&#x27;s Skill Package Mess Up My AI?: Three Things I Do Before Copying One",
    "summary": "Asking an AI to check whether something is safe is worth doing, but its conclusion is only a lead. More common than malicious code is workflow conflict. This article gives a three-layer source check, why asking the AI to check is unreliable and what to do instead, the four things that actually matter about permissions, four options when workflows conflict, and how to audit the packages you have already installed.",
    "date": "2026-08-05",
    "url": "articles/before-installing-others-skill/"
  },
  {
    "slug": "use-more-ai-not-enough",
    "title": "Most People Are Simply Using More AI. The Shape of Work Hasn't Changed",
    "summary": "Three lessons from a 69-minute Sam Altman interview: lay foundations before they are cost-effective, externalize judgments that are hard to teach, and use persistence plus multiple filters to find AI-native opportunities.",
    "date": "2026-07-30",
    "url": "articles/use-more-ai-not-enough/"
  },
  {
    "slug": "messaging-apps-ai-friendliness",
    "title": "How AI-Friendly Are Messaging Apps?",
    "summary": "A six-metric comparison of LINE, Telegram, Discord, and Slack across AI features, AI membership, moderation, community structure, and Agent workflows, with mid-2026 updates, official sources, three decision questions, and a copyable test prompt.",
    "date": "2026-07-29",
    "url": "articles/messaging-apps-ai-friendliness/"
  },
  {
    "slug": "ai-employee-four-levels",
    "title": "Four Levels of Training AI Employees: From Using AI Yourself to Letting AI Train AI",
    "summary": "Four levels of training AI employees, four steps for training the first one, two sets of ten copyable questions, and criteria for deciding which work AI can safely take over.",
    "date": "2026-07-28",
    "url": "articles/ai-employee-four-levels/"
  },
  {
    "slug": "talent-vs-expertise",
    "title": "What Feels Easy May Be Talent; What Takes Effort to Learn Is Professional Skill",
    "summary": "Why talent often feels so easy that you overlook it, how that makes it a hidden form of tacit knowledge, and two self-guided distillation exercises with copyable questions.",
    "date": "2026-07-26",
    "url": "articles/talent-vs-expertise/"
  },
  {
    "slug": "answer-to-action-enterprise-ai-agent",
    "title": "From Answers to Action: How I Think About Enterprise AI Agent Adoption",
    "summary": "Using Professor Jian Lifeng",
    "date": "2026-07-25",
    "url": "articles/answer-to-action-enterprise-ai-agent/"
  },
  {
    "slug": "agent-web-turning-point",
    "title": "More Than Half of Web Traffic Is No Longer Human. Is Your Content Ready for Machines?",
    "summary": "A source-layered look at Cloudflare",
    "date": "2026-07-25",
    "url": "articles/agent-web-turning-point/"
  },
  {
    "slug": "long-task-completion-rate",
    "title": "Opus 5 Test: How Far Can Your AI Get Through a 10-Step Loop Before It Stops?",
    "summary": "A ten-step knowledge-work test across Opus 4.8, Fable, and Opus 5 Max, a definition of long-workflow completion rate, three responses to an unsolved fifth step, and a copyable continuation command.",
    "date": "2026-07-25",
    "url": "articles/long-task-completion-rate/"
  },
  {
    "slug": "ai-tools-professional-judgment",
    "title": "When Everyone Has AI, Judgment Is the Real Differentiator",
    "summary": "A three-engineer AI code-cleaning service, priced at up to $10,000 per week, shows why human cognition, judgment, and industry knowledge remain scarce even when everyone has access to AI tools.",
    "date": "2026-07-17",
    "url": "articles/ai-tools-professional-judgment/"
  },
  {
    "slug": "chatgpt-work-codex-choice",
    "title": "ChatGPT Work, Codex, or Standard ChatGPT: How Should You Divide the Work?",
    "summary": "A practical way to divide work among ChatGPT Work, Codex, and standard ChatGPT based on local data, long-term knowledge bases, Projects, Skills, MCP, and usage limits.",
    "date": "2026-07-16",
    "url": "articles/chatgpt-work-codex-choice/"
  },
  {
    "slug": "old-prompts-intent-first-loop-engineering",
    "title": "Keep Your Old Prompts: Extract the Intent, Then Move Toward Loop Engineering",
    "summary": "Old prompts and skill packages still contain your standards, preferences, and red lines. Learn how to turn them into intent references and connect them to loop engineering with a copyable prompt and a minimal workflow.",
    "date": "2026-07-16",
    "url": "articles/old-prompts-intent-first-loop-engineering/"
  },
  {
    "slug": "personal-studio-vs-solo-company",
    "title": "Personal Studio vs. Solo Company: Two Differences That Matter to Me",
    "summary": "Two distinctions between a personal studio and a solo company, plus a five-step method and three skill packages for turning professional expertise into a repeatable commercial system.",
    "date": "2026-07-16",
    "url": "articles/personal-studio-vs-solo-company/"
  },
  {
    "slug": "train-your-ai-agent-editor",
    "title": "Train Your AI Agent: Help AI Understand You Instead of Learning Every Tool",
    "summary": "A course-derived guide to turning your data, judgment, style, and workflow into a knowledge base an AI Agent can use, with nine sections of copyable prompts.",
    "date": "2026-07-16",
    "url": "articles/train-your-ai-agent-editor/"
  },
  {
    "slug": "post-class-organizing-loop",
    "title": "After a class is over, how do I transform it into reusable knowledge?",
    "summary": "Decomposing the Post-Class Organizing Loop: How One After-Class Material Can Yield Three Products - A Teaching Manual, an After-Class Recording Slide Presentation, and an Online Course Page on Our Website. The Six-Step Pipeline and My Two-Level Review Process Are Explained in Detail. Here’s a Template You Can Follow.",
    "date": "2026-07-15",
    "url": "articles/post-class-organizing-loop/"
  },
  {
    "slug": "ai-handoff-instructions",
    "title": "AI Handoff Instructions: The Hard Part Is Deciding What to Leave Out",
    "summary": "A real incident showing how AI handoff instructions fail when they include too much, followed by three handoff scenarios and a reusable handoff form.",
    "date": "2026-07-15",
    "url": "articles/ai-handoff-instructions/"
  },
  {
    "slug": "ai-cp-value-calculus",
    "title": "Choosing AI Models by Value for Money",
    "summary": "A task-first way to choose AI models by actual capability needs and value for money, with three comparison tables and a deeper question about which problems are worth solving.",
    "date": "2026-07-14",
    "url": "articles/ai-cp-value-calculus/"
  },
  {
    "slug": "mika-to-laika-product-character-design",
    "title": "When an AI Assistant Changes Platforms, Its Capabilities Change: Why I Split One Role into Two",
    "summary": "Three questions for deciding when an AI assistant should keep one identity across platforms and when its role, name, and appearance should split to make product boundaries clear.",
    "date": "2026-07-14",
    "url": "articles/mika-to-laika-product-character-design/"
  },
  {
    "slug": "chatgpt-work-skills-web-version",
    "title": "ChatGPT on the Web Finally Supports Skill Packages: From Setup to Two Pitfalls",
    "summary": "How ChatGPT Work brings skill packages to the web, how skill packages differ from prompts, how projects store data while skill packages store judgment, and two pitfalls that appear with deeper use.",
    "date": "2026-07-13",
    "url": "articles/chatgpt-work-skills-web-version/"
  },
  {
    "slug": "inspiration-production-system",
    "title": "The Inspiration Production System",
    "summary": "Inspiration can be produced systematically. Build an inspiration pool for content creation: three sources of inspiration (past accumulated content, AI-simulated audiences, and hot topics) plus a tag-retrieval system that turns posts with your personal voice into a system that runs on its own. Coach Jiang shares the hands-on method from two of his classes.",
    "date": "2026-07-13",
    "url": "articles/inspiration-production-system/"
  },
  {
    "slug": "dual-track-planning-loop",
    "title": "Let Two AIs Catch Each Other's Mistakes: My Plan Scored 2/5 From a Mock Review Before I Sent It",
    "summary": "AI writes plans fast, but the catch is that it goes along with you: one model writes and reviews itself and never sees its own blind spots. Using a real government-grant proposal, this article documents the full dual-track mutual-review loop: two AIs from different companies each write the plan independently, catch each other",
    "date": "2026-07-12",
    "url": "articles/dual-track-planning-loop/"
  },
  {
    "slug": "agent-native-tools-software-interface",
    "title": "Will Agent-Native Tools Push Software Interfaces into the Background?",
    "summary": "When AI can receive tasks, plan steps, and return reviewable work, software interfaces may move into the background. An outsourcing-team analogy explains how I delegate with tasks, budgets, and acceptance criteria.",
    "date": "2026-07-12",
    "url": "articles/agent-native-tools-software-interface/"
  },
  {
    "slug": "laptop-desktop-webpage-sync-icloud-git",
    "title": "Built a webpage with Codex on your home desktop, then can't find the files to edit on your laptop? The problem is where you stored the project",
    "summary": "Finished a webpage on your desktop, then can",
    "date": "2026-07-11",
    "url": "articles/laptop-desktop-webpage-sync-icloud-git/"
  },
  {
    "slug": "dual-centaur-meeting",
    "title": "Dual-Centaur Meeting: I Bring My Agent, You Bring Your Agent, Four Parties Meet Together",
    "summary": "Complex-project meetings often run two or three hours just to align on goals, yet handing everything to AI agents loses the details. The dual-centaur meeting is the middle path: a person plus their Agent meets another person plus their Agent. Agents filter the data first; people discuss only decisions, trust, and commitment. Includes a five-step workflow and the PAAP, AAP, AA evolution.",
    "date": "2026-07-11",
    "url": "articles/dual-centaur-meeting/"
  },
  {
    "slug": "knowledge-os-master-map",
    "title": "The Knowledge Operating System: A Master Architecture for Turning Tacit Knowledge into Executable Judgment",
    "summary": "A Knowledge Operating System framework built from three repositories, an eight-step refinement loop, barriers, governance, and a three-domain deployment axis, supported by convergence evidence and three real workflow tests.",
    "date": "2026-07-10",
    "url": "articles/knowledge-os-master-map/"
  },
  {
    "slug": "strong-ai-models-knowledge-workflow-road",
    "title": "The model is the supercar; your knowledge base and workflow are the road beneath it",
    "summary": "Once strong models like Claude Fable and GPT-5.6 Sol arrive, the gaps created by your knowledge base, workflow, rules and acceptance criteria become far more obvious. Three kinds of road walk you through a six-step process for paving the way for AI.",
    "date": "2026-07-10",
    "url": "articles/strong-ai-models-knowledge-workflow-road/"
  },
  {
    "slug": "knowledge-as-employee",
    "title": "Treat Knowledge as an Employee: The New Divide in AI-Era Knowledge Management",
    "summary": "How knowledge management changes when structured knowledge can work alongside AI, with tacit knowledge distillation as the central capability and seven dimensions for comparing the two approaches.",
    "date": "2026-07-10",
    "url": "articles/knowledge-as-employee/"
  },
  {
    "slug": "meeting-into-verifiable-loop",
    "title": "I Turned a Meeting Summary into a Verifiable Delivery Loop",
    "summary": "How a recurring meeting-summary process, already documented as skill packages, became a one-command delivery loop with built-in verification.",
    "date": "2026-07-07",
    "url": "articles/meeting-into-verifiable-loop/"
  },
  {
    "slug": "publish-gate",
    "title": "How to Keep Multiple AIs Editing the Same Website From Clashing",
    "summary": "Maintain a website with AI long enough and version chaos is inevitable: one task edits here, another edits there, and they overwrite each other. Using a real screw-up of my own, this article lays out a three-layer safeguard you can actually set up: workspace isolation, a publish gate, and enforcement, with a ready-to-use public skill package.",
    "date": "2026-07-06",
    "url": "articles/publish-gate/"
  },
  {
    "slug": "loop-engineering-guardrails",
    "title": "Loop Guardrails: Five rules that let AI run on its own without running past the safety limits",
    "summary": "Five guardrails that join Harness Engineering and Loop Engineering: undefended assumptions, three-angle challenge, Non-goals and allowed paths, change-course braking, and grading acceptance evidence. So that when AI works continuously and automatically, a single error doesn",
    "date": "2026-07-06",
    "url": "articles/loop-engineering-guardrails/"
  },
  {
    "slug": "questionnaire-to-slides-agent-workflow",
    "title": "Turn the pre-class questionnaire into a presentation, and then save the process into a skill package",
    "summary": "One class Agent basic teaching demonstration and formal SOP: organize the teaching presentation from the pre-class questionnaire and syllabus, and then condense the steps of making the presentation into the Agent workflow, lecture-prep skill package and knowledge base. Suitable for AI novices, lecturers and consultants to read first.",
    "date": "2026-07-06",
    "url": "articles/questionnaire-to-slides-agent-workflow/"
  },
  {
    "slug": "map-is-not-the-territory",
    "title": "The Map Is Not the Territory",
    "summary": "When working with AI, what really gets you stuck is often that the map you hand over is too simple, and no matter how powerful the model, it can",
    "date": "2026-07-05",
    "url": "articles/map-is-not-the-territory/"
  },
  {
    "slug": "ai-changed-behavior-into-workflow",
    "title": "Catch the Behavior AI Quietly Changed, and Turn It Into a Workflow",
    "summary": "On a business trip, I noticed my first move for planning a route had shifted from opening the map to asking AI. Starting from that case, this piece teaches you to spot these quietly AI-changed behaviors, and, following Loop Engineering, turn them into a repeatable workflow in four steps (find the behavior, observe the variables, fix the process, make it a prompt). A copy-paste prompt is included at the end.",
    "date": "2026-07-04",
    "url": "articles/ai-changed-behavior-into-workflow/"
  },
  {
    "slug": "prompt-to-loop-map",
    "title": "From Prompt to Loop Engineering",
    "summary": "Prompt engineering, context engineering, steering engineering, loop engineering. These four stages form one spine that strings together the twenty-odd related articles I have written. Enter at any station and read down.",
    "date": "2026-07-02",
    "url": "articles/prompt-to-loop-map/"
  },
  {
    "slug": "recovery-over-perfection",
    "title": "Instead of Expecting an Error-Free AI System, Design a Fault-Tolerant Loop",
    "summary": "AI will make mistakes, and people give wrong instructions too, so an error-free system is impossible. This piece organizes how I redirect the effort toward fault tolerance: six steps (sort by size, keep an exit, small test first, batch with a trail, verify with a different mind, write a wrap-up note), each with a completion condition and its common pitfall, plus a full worked example.",
    "date": "2026-07-02",
    "url": "articles/recovery-over-perfection/"
  },
  {
    "slug": "harness-mindset-for-bosses",
    "title": "The Boss’s Steering Mindset: Say to AI What You Would Never Say to an Employee",
    "summary": "Many bosses think using AI means learning a pile of new tools. But it is the Agent era now: AI can already work as an employee, and you can be ten times harder on it. This covers the steering mindset, with the ten steering questions, inward questioning, and a good-boss comparison, all copy-paste.",
    "date": "2026-07-02",
    "url": "articles/harness-mindset-for-bosses/"
  },
  {
    "slug": "ai-loop-safety-recovery",
    "title": "AI Errors Aren't the Danger, Having No Backup Is: Lessons From Corrupting 170 Files",
    "summary": "A fully autonomous rename task corrupted 170 files, and the AI still reported",
    "date": "2026-07-01",
    "url": "articles/ai-loop-safety-recovery/"
  },
  {
    "slug": "ai-delegators-optimism",
    "title": "The more you hand work to AI, the more you want it stronger, and the less you fear replacement",
    "summary": "From Anthropic",
    "date": "2026-07-01",
    "url": "articles/ai-delegators-optimism/"
  },
  {
    "slug": "tag-wiki-method",
    "title": "Turn Tags Into Cards, and Your Knowledge Base Comes Alive: The Tag Wiki Method",
    "summary": "Upgrade a tag from a keyword you stick on to a card with real content. Controlled across four dimensions, almost no YAML, and a clear account of how this method complements dense interlinking and RAG rather than replacing them.",
    "date": "2026-07-01",
    "url": "articles/tag-wiki-method/"
  },
  {
    "slug": "give-ai-choices-not-descriptions",
    "title": "Give AI Choices, Not Descriptions: Six Color Palettes at Once, Then Fine-Tune",
    "summary": "The slowest part of working with AI on styles is the endless back-and-forth guessing. Change your prompt: ask for six palettes side by side, pick the one you like, fine-tune on the spot, and copy the final CSS in one click. Three steps, no repeated descriptions. Includes a live demo.",
    "date": "2026-06-30",
    "url": "articles/give-ai-choices-not-descriptions/"
  },
  {
    "slug": "company-shape-is-the-moat",
    "title": "The Real Moat in the AI Era: Organizational Shape, Shared Consensus, Influence, and User Trust",
    "summary": "In the AI era, products, technology, and categories are all being replicated at speed. Investor Jaya Gupta argues the moat is the shape a company grows into. Here I synthesize her argument and add a more concrete take: organizational patterns are like skeletons that can be copied. What truly cannot be taken is consensus, influence, and user trust, things that only accumulate over time.",
    "date": "2026-06-30",
    "url": "articles/company-shape-is-the-moat/"
  },
  {
    "slug": "four-lens-rapid-review",
    "title": "When Busy Becomes Directionless: A Four-Lens Rapid Review",
    "summary": "Running multiple projects at once, staying busy but losing clarity? This six-step rapid review (spread the facts, feedback-leverage matrix, four-lens audit, externalization filter, converge to one action) helps you recalibrate. Runs on a single sheet of paper.",
    "date": "2026-06-30",
    "url": "articles/four-lens-rapid-review/"
  },
  {
    "slug": "my-three-loops",
    "title": "When I Started Thinking in Loops: Three Workflows Redesigned as Loops",
    "summary": "From writing prompts to designing loops. I took three workflows I was already running and turned them into three named loops: a publishing loop (outward), a tacit-knowledge distillation loop (inward), and a retrospective loop (backward), all orbiting the same knowledge base.",
    "date": "2026-06-30",
    "url": "articles/my-three-loops/"
  },
  {
    "slug": "market-to-ai",
    "title": "Two Things You Can Learn Right Now: Using AI for Marketing, and Marketing to AI",
    "summary": "When AI starts making decisions on people",
    "date": "2026-06-29",
    "url": "articles/market-to-ai/"
  },
  {
    "slug": "a2a-agent-protocol",
    "title": "AI Agents Are Taking Over Your Workflows. Are Your Processes and Knowledge Ready?",
    "summary": "As AI agents begin delegating tasks to each other, the real bottleneck is not technology. It is whether your organization",
    "date": "2026-06-28",
    "url": "articles/a2a-agent-protocol/"
  },
  {
    "slug": "intangible-assets-grow-by-sharing",
    "title": "Intangible Assets Grow by Sharing",
    "summary": "Intangible assets grow the more you share them. In the AI era, experience, thinking, and judgment can be amplified by AI into knowledge capital. From content creation to a digital chamber of commerce, sharing my path to becoming an intangible capitalist.",
    "date": "2026-06-28",
    "url": "articles/intangible-assets-grow-by-sharing/"
  },
  {
    "slug": "intent-first-prompting",
    "title": "Stop Writing Rigid Instructions: Say What You Want, Let AI Handle the Rest",
    "summary": "In 2024 everyone rushed to learn prompts. The game has changed. AI is now smart enough to think of better approaches than you, and locking it into rigid instructions wastes that. This is the core mindset of steering engineering: intent first, with three copy-paste prompts.",
    "date": "2026-06-27",
    "url": "articles/intent-first-prompting/"
  },
  {
    "slug": "parenting-story-ai-family-dialogue",
    "title": "Use AI to turn parent-child daily life into stories, illustrations and family conversation materials",
    "summary": "Complete record of the parent-child storytelling AI workshop: the guidance method of the Red Tomato Agreement, script and illustration prompts, live-action movie poster techniques, five finished products from a parent-child story, and finally back to family dialogue.",
    "date": "2026-06-27",
    "url": "articles/parenting-story-ai-family-dialogue/"
  },
  {
    "slug": "what-is-loop-engineering",
    "title": "What Is Loop Engineering? Explained Through My Article-Writing Workflow",
    "summary": "What is loop engineering? No code required. Coach Jiang explains the concept through his article-writing workflow: the difference between prompts and loops, the five phases of a loop, the minimum required components, and when it is actually worth building one.",
    "date": "2026-06-27",
    "url": "articles/what-is-loop-engineering/"
  },
  {
    "slug": "tidy-mess-before-consulting",
    "title": "Tidy the Mess Before Consulting: Let AI Turn Chaos into a Question",
    "summary": "Can",
    "date": "2026-06-26",
    "url": "articles/tidy-mess-before-consulting/"
  },
  {
    "slug": "ai-capability-tiers",
    "title": "Where Do You Stand in the AI World? A 14-Tier Capability Ranking by Industry Impact",
    "summary": "Coach Jiang",
    "date": "2026-06-26",
    "url": "articles/ai-capability-tiers/"
  },
  {
    "slug": "vibe-coding-ten-half-products",
    "title": "You Think You Are Building One Product. You Are Actually Raising Ten Half-Finished Ones.",
    "summary": "A short interview video uses an addiction metaphor to trace one person",
    "date": "2026-06-26",
    "url": "articles/vibe-coding-ten-half-products/"
  },
  {
    "slug": "docs-as-system-design-agent",
    "title": "Docs as System Design: How Non-Engineers Build Agent Frameworks",
    "summary": "You don",
    "date": "2026-06-25",
    "url": "articles/docs-as-system-design-agent/"
  },
  {
    "slug": "how-ai-connects-software",
    "title": "How AI Agents Connect to Software Directly",
    "summary": "Today",
    "date": "2026-06-24",
    "url": "articles/how-ai-connects-software/"
  },
  {
    "slug": "decision-ladder-non-programmer",
    "title": "Ponytail: The \"Decision Ladder\" for People Who Don't Write Code",
    "summary": "Ponytail started as an engineering skill for trimming AI-generated over-engineered code. What it actually solves is universal: AI that says too much. This article moves the decision ladder from code to writing, organizing, and training AI employees, and explains the key that makes it work: burden reversal.",
    "date": "2026-06-24",
    "url": "articles/decision-ladder-non-programmer/"
  },
  {
    "slug": "codex-log-health-check",
    "title": "Codex Crashed? Check logs_2.sqlite First After Reinstalling",
    "summary": "When Codex Desktop won",
    "date": "2026-06-23",
    "url": "articles/codex-log-health-check/"
  },
  {
    "slug": "meeting-record-agent-workflow",
    "title": "My Meeting-Record Agent Workflow",
    "summary": "Starting from in-person recording, OBS online screen capture, and MacWhisper or VibeVoice-ASR transcription, then step by step adding on-the-ground observations, preserving the raw material, generating a meeting strategy report and first-draft deliverables, and finally using multiple thinking models to check for blind spots.",
    "date": "2026-06-23",
    "url": "articles/meeting-record-agent-workflow/"
  },
  {
    "slug": "line-group-ai-workflow",
    "title": "How to Auto-Archive Data Scattered Across LINE Groups Every Day",
    "summary": "A one-page guide to automatically downloading messages, images, PDFs, and files scattered across LINE groups via an official account, organizing them into folders by group, and handing the results to an Agent.",
    "date": "2026-06-22",
    "url": "articles/line-group-ai-workflow/"
  },
  {
    "slug": "elon-musk-live-skill",
    "title": "The Live Elon Musk Skill",
    "summary": "A deep-dive introduction to the Live Elon Musk Skill. It distills Elon Musk",
    "date": "2026-06-22",
    "url": "articles/elon-musk-live-skill/"
  },
  {
    "slug": "how-to-train-your-ai-employee",
    "title": "Build Your AI Employees + Consultants",
    "summary": "Teaching slides from a hands-on workshop: set up AI as your employee to work the way you do, then add a panel of consultants to challenge your blind spots. Covers org structure, the seven-layer tacit knowledge distillation system, connecting nodes into workflows, and how to judge what a problem is worth.",
    "date": "2026-06-21",
    "url": "articles/how-to-train-your-ai-employee/"
  },
  {
    "slug": "ai-market-microcosm",
    "title": "AI Is a Microcosm of the Entire Market",
    "summary": "Market research is slow and costly, but AI has been trained on vast amounts of real human writing and is itself a microcosm of the market. Research by Colgate and PyMC Labs confirms that asking AI to write reactions first and then convert them into scores can simulate purchase intent to within 90% of human self-consistency. Includes a copy-paste prompt and a free skill package.",
    "date": "2026-06-20",
    "url": "articles/ai-market-microcosm/"
  },
  {
    "slug": "own-ai-team-at-work",
    "title": "You Can Have Your Own AI Team Even as a Company Employee",
    "summary": "You can choose to see yourself as an employee, or as the owner of a company of one with your employer as your only long-term client. Same job, different mindset. And without that shift, you will never build your own AI team.",
    "date": "2026-06-20",
    "url": "articles/own-ai-team-at-work/"
  },
  {
    "slug": "knowledge-base-three-vault-split",
    "title": "My Knowledge Base Got Too Big, So I Split It Three Ways",
    "summary": "When a knowledge base grows too large to navigate, ask one question: who actually uses this? That single question splits everything into three vaults (main, secondary, and public-facing) with a simple filing workflow and one clear exception.",
    "date": "2026-06-19",
    "url": "articles/knowledge-base-three-vault-split/"
  },
  {
    "slug": "ai-king-off-battlefield",
    "title": "The AI King Stays Off the Battlefield",
    "summary": "This is not a prediction, and I have no inside information. I want to offer a different lens for reading AI trends: stop fixating on benchmark scores. As models become increasingly commoditized, what may truly be scarce is the access point. Apple and Google, often criticized for weaker models, may be the ones dispatching orders from behind the throne.",
    "date": "2026-06-17",
    "url": "articles/ai-king-off-battlefield/"
  },
  {
    "slug": "codex-only-auto-worklog",
    "title": "Building Your Own Automatic Work Log with Codex Alone",
    "summary": "Many people lose track of their work context soon after they start using AI agents. This article offers two paths: if you only use Codex, its built-in automation is all you need; if you use multiple agents, you need a cross-agent work mirror. Includes three copy-ready Codex work log prompts.",
    "date": "2026-06-16",
    "url": "articles/codex-only-auto-worklog/"
  },
  {
    "slug": "agent-workflow-builds-automation",
    "title": "I Used an Agent to Build My Automated Workflow",
    "summary": "Automation is best understood as two distinct concepts: an Agent workflow builds the process for you, while a programmatic automation workflow runs it on its own. Using a Codex-powered LINE backup bot as a case study, this article breaks down how the two work together and gives you a practical framework for deciding what to hand off to AI and what to hand off to code.",
    "date": "2026-06-16",
    "url": "articles/agent-workflow-builds-automation/"
  },
  {
    "slug": "youtube-to-opinion-report-workflow",
    "title": "A complete workflow for turning a YouTube video into an opinion report webpage",
    "summary": "A complete demonstration of turning YouTube videos into opinion report webpages: NotebookLM conversion to verbatim drafts, desktop Agent local organization, design skill package layout, plus the way of thinking about task submission, acceptance, and accumulation of skill packages.",
    "date": "2026-06-14",
    "url": "articles/youtube-to-opinion-report-workflow/"
  },
  {
    "slug": "caught-ai-slacking-into-rules",
    "title": "I Caught My AI Slacking, Then Wrote It Into the Rules",
    "summary": "I asked Codex to call Claude to revise an article. It never actually called Claude, yet returned what looked like a finished result. This is the retrospective: how to verify whether an AI truly executed an external action, and how to turn each failure into a rule that gets enforced next time.",
    "date": "2026-06-08",
    "url": "articles/caught-ai-slacking-into-rules/"
  },
  {
    "slug": "yongli-ai-workshop-tools-to-workflow",
    "title": "Chamber of Commerce One-Day AI Workshop: From Tool Understanding to Workflow and Knowledge Base",
    "summary": "A full record of a one-day AI workshop for a chamber of commerce: from dismantling tool anxiety and understanding AI",
    "date": "2026-05-30",
    "url": "articles/yongli-ai-workshop-tools-to-workflow/"
  },
  {
    "slug": "diary-driven-agent-3x4",
    "title": "Write a Diary, Put AI to Work",
    "summary": "You don",
    "date": "2026-05-28",
    "url": "articles/diary-driven-agent-3x4/"
  },
  {
    "slug": "teacher-prep-knowledge-workflow",
    "title": "How lecturers use knowledge management processes to turn lesson preparation into a reusable system",
    "summary": "An Agent lesson-prep workflow for lecturers, consultants and knowledge workers: from finding information, an inspiration pool, pre-class questionnaires, promotion, lesson prep and deliverables, to post-class repurposing and cross-course reuse.",
    "date": "2026-05-23",
    "url": "articles/teacher-prep-knowledge-workflow/"
  },
  {
    "slug": "relationship-boundary-ai-practice",
    "title": "Use AI to practice subject separation, return of responsibility and emotional response",
    "summary": "A full write-up of the Relationship Without Internal Friction Practice Course: guidance methods for subject separation and returning responsibility, two AI practice modes (cold analysis and hot companionship), perspective translation and handling resistance, and the all-important red line list. AI is a practice ground, not psychotherapy.",
    "date": "2026-05-20",
    "url": "articles/relationship-boundary-ai-practice/"
  },
  {
    "slug": "web-chat-ai-vs-desktop-agent",
    "title": "Web-based chat AI vs. desktop work AI: Codex is a GPT desktop version installed on your computer",
    "summary": "A beginner-friendly guide to the boundaries between chat AI, single-purpose web tools, and desktop agents: three pain points of project mode, the paradigm shift of the desktop era, Codex, and a three-layer division-of-labor workflow. Liberal arts folks can pick it up without writing code.",
    "date": "2026-05-11",
    "url": "articles/web-chat-ai-vs-desktop-agent/"
  },
  {
    "slug": "books-videos-pdf-ai-advisor",
    "title": "Convert books, videos, and PDFs into conversational AI consultants",
    "summary": "A complete method for turning external materials into an AI consultant that can be questioned: sorting out sources, extracting thinking framework, writing consultant settings, and verifying compatibility. Take the real-life case of turning Naval’s books and interviews into digital clones.",
    "date": "2026-05-03",
    "url": "articles/books-videos-pdf-ai-advisor/"
  },
  {
    "slug": "liberal-arts-agent-framework",
    "title": "Liberal arts majors can hand their work to AI without writing code: designing your own Agent framework",
    "summary": "A general-education course on Agent framework design for non-coders: the three parts of Harness Engineering, Loop Engineering and three kinds of journals, the LLM Wiki knowledge graph and the Tag Wiki tag system. You can hand your work to AI without writing code.",
    "date": "2026-04-20",
    "url": "articles/liberal-arts-agent-framework/"
  },
  {
    "slug": "ai-learning-map-reduce-anxiety",
    "title": "Use AI to build a trackable learning map to reduce information anxiety",
    "summary": "Bookmarks folder full of things saved for later? Use an Agent to organize learning materials scattered everywhere into one visible learning map: skill tree, learning record, personal profile. A three-layer structure with teacher lesson-plan and scheduling-system cases.",
    "date": "2026-03-29",
    "url": "articles/ai-learning-map-reduce-anxiety/"
  },
  {
    "slug": "ai-course-map-from-entry-to-workflow",
    "title": "From entry to workflow: Coach Jiang’s AI course map",
    "summary": "A vertically structured AI course map: an Agent onboarding foundation at the center, applying ready-made workflows going up, and three deep-dive lines going down (data organization, tacit knowledge distillation, and semantic engineering). It all converges on an Agent-powered solo-company operations team.",
    "date": "2026-03-20",
    "url": "articles/ai-course-map-from-entry-to-workflow/"
  },
  {
    "slug": "ai-data-organization-usable-system",
    "title": "How to organize data in the AI era and turn files into usable systems",
    "summary": "The complete method from my AI-era data organization foundations class: use four Markdown syntaxes, carding, linking, and controlled vocabulary to turn your files into a system both people and AI can use, with copy-paste prompts included.",
    "date": "2026-03-09",
    "url": "articles/ai-data-organization-usable-system/"
  },
  {
    "slug": "claude-skills-knowledge-assets",
    "title": "What Are Claude Skills? Turn Your Professional Workflow into a Knowledge Asset AI Can Run Again and Again",
    "summary": "Understand skill packages through Claude Skills: a skill package is an operation manual written for AI that packages your professional workflow, format standards, and best state into a knowledge asset that can be run repeatedly. Includes two ways to build one, plus backup tips.",
    "date": "2026-02-28",
    "url": "articles/claude-skills-knowledge-assets/"
  },
  {
    "slug": "semantic-rules-before-prompt-templates",
    "title": "Why Are Prompt Templates Hit-or-Miss? First Understand That AI Is a Phone Keyboard, 100 Million Times More Powerful",
    "summary": "The underlying logic of prompt design: AI is a word-association calculator, like a phone keyboard 100 million times more powerful. From the three-step fix for task separation and the limits of role-setting to the trap of negative prompts, understand the semantics before you reach for a template.",
    "date": "2026-01-24",
    "url": "articles/semantic-rules-before-prompt-templates/"
  },
  {
    "slug": "notebooklm-knowledge-analysis-assistant",
    "title": "How NotebookLM Goes from a Data-Organizing Tool to a Knowledge-Analysis Assistant",
    "summary": "A full guide to NotebookLM: evolving from having AI summarize for you to having the report read you. Personal profiles, multi-source knowledge bases, a real cross-field syllabus collaboration case, plus two organizing tips — the PDF trap and Markdown content boundaries.",
    "date": "2026-01-04",
    "url": "articles/notebooklm-knowledge-analysis-assistant/"
  },
  {
    "slug": "ai-mvp-validation-before-product",
    "title": "Validate Your Startup Idea with AI Before Spending Big on a Product",
    "summary": "Customers say it",
    "date": "2025-09-10",
    "url": "articles/ai-mvp-validation-before-product/"
  },
  {
    "slug": "one-on-one-questions",
    "title": "37 Common AI Questions: Building Knowledge Bases, Using Skill Packages, and Driving Adoption",
    "summary": "Complete answers to 37 real questions from a free one-on-one online session, covering knowledge bases, skill packages, model choice, AI verification, and organizational adoption, with 26 links to deeper articles.",
    "date": "",
    "url": "articles/one-on-one-questions/"
  },
  {
    "slug": "demis-hassabis-agi-science-ai",
    "title": "At the foot of AGI, what is truly being rewritten are the rules of the scarcity era.",
    "summary": "Coach Jiang",
    "date": "",
    "url": "ai-trends/demis-hassabis-agi-science-ai/"
  },
  {
    "slug": "ai-that-knows-you",
    "title": "Help AI Understand You Better: From Knowing You to Helping You Act",
    "summary": "Three settings you can complete on a phone in ten minutes to give AI more useful context about you and help it move from conversation toward practical assistance.",
    "date": "",
    "url": "articles/ai-that-knows-you/"
  },
  {
    "slug": "timing-and-forecast",
    "title": "Information Lag and Market Forecasting: How to Get Ahead Without Moving Too Early",
    "summary": "A timeline of how overseas ideas reach Taiwan, a three-step forecasting method, and two questions for deciding where you are now and what to prepare next.",
    "date": "",
    "url": "articles/timing-and-forecast/"
  },
  {
    "slug": "program-vs-ai-skill-library",
    "title": "Let Code Handle What's Certain; AI Is for What Isn't",
    "summary": "When companies try to adopt AI, they often get stuck not knowing where to deploy it or how to make AI actually do their company",
    "date": "",
    "url": "ai-trends/program-vs-ai-skill-library/"
  },
  {
    "slug": "manage-ai-with-management-knowledge",
    "title": "Manage AI with the Management Knowledge You Already Have: Toyota TPS as an Example",
    "summary": "How management knowledge about people, processes, and quality can translate into AI workflows, using Toyota TPS as the example and ending with a practical translation checklist.",
    "date": "",
    "url": "articles/manage-ai-with-management-knowledge/"
  },
  {
    "slug": "apple-wwdc26-siri-lobster-ai",
    "title": "Siri Is Finally Evolving toward \"Lobster AI.\"",
    "summary": "Coach Jiang",
    "date": "",
    "url": "ai-trends/apple-wwdc26-siri-lobster-ai/"
  },
  {
    "slug": "ten-year-anchor",
    "title": "Solving AI Knowledge Anxiety: Finding an Anchor That Holds for Ten Years",
    "summary": "A practical way to find a ten-year anchor in a fast-changing AI landscape, keep the underlying task steady as tools change, and delegate information filtering to AI with a copyable prompt.",
    "date": "",
    "url": "articles/ten-year-anchor/"
  },
  {
    "slug": "spacex-ipo-musk-trillionaire-knowledge-work",
    "title": "The Path the World's Richest Man Has Pointed Out for Knowledge Workers, With a Trillion Dollars.",
    "summary": "Coach Jiang",
    "date": "",
    "url": "ai-trends/spacex-ipo-musk-trillionaire-knowledge-work/"
  },
  {
    "slug": "cli-api-mcp-computer-use",
    "title": "Want AI to Order Food? CLI, API, and MCP Explained",
    "summary": "CLI, API, MCP, and Computer Use explained through the metaphor of asking AI to order food, with terminology, principles, scenarios, behaviors, and a practical order for choosing a channel.",
    "date": "",
    "url": "articles/cli-api-mcp-computer-use/"
  },
  {
    "slug": "free-deploy-three-boundaries",
    "title": "Where Should You Put an AI-Built Website? GitHub Pages vs. Vercel",
    "summary": "Three questions for deciding where to host an AI-built website, a four-layer model based on content sensitivity, and a source-backed comparison of GitHub Pages and Vercel quotas, source-code visibility, access control, and costs.",
    "date": "",
    "url": "articles/free-deploy-three-boundaries/"
  },
  {
    "slug": "ai-native-not-transformation",
    "title": "Why AI Adoption Fails: From a Three-Layer Model to Organizational Barriers",
    "summary": "A three-layer model for understanding AI adoption, followed by the organizational barrier that appears when efficiency rises tenfold while compensation stays unchanged.",
    "date": "",
    "url": "articles/ai-native-not-transformation/"
  },
  {
    "slug": "rule-file-rebound",
    "title": "Why Most of Your AI Rules Never Run",
    "summary": "After my rule files grew back within 18 days, I reviewed about 220 rules and found only 24 with execution mechanisms. This article provides a four-column audit, three admission questions, a no-Hook manual version, and a weekly review schedule.",
    "date": "",
    "url": "articles/rule-file-rebound/"
  },
  {
    "slug": "why-split-data-into-cards",
    "title": "Why Split Data into Cards? From PDF Readability to Card-Based AI Retrieval",
    "summary": "An interactive guide showing how slide decks and PDFs affect AI retrieval, how accuracy changes as data volume grows, and how cards can be split, retrieved by tag, and recombined for new uses.",
    "date": "",
    "url": "articles/why-split-data-into-cards/"
  },
  {
    "slug": "teach-ai-not-learn-ai",
    "title": "Why Your AI Starts Over Every Time: Four Steps to Teaching It",
    "summary": "Four steps for teaching AI your judgment: separate three repository types, organize files with the 3X4 method, write an executable rule, and transfer the way you guide people.",
    "date": "",
    "url": "articles/teach-ai-not-learn-ai/"
  }
];
