/* Generated by scripts/build-en-articles-data.mjs. */
window.EN_ARTICLES = [
  {
    "slug": "post-class-organizing-loop",
    "title": "After a class is over, how do I transform it into reusable knowledge?",
    "summary": "Decomposing the Post-Class Organizing Loop: How One After-Class Material Can Yield Three Products - A Teaching Manual, an After-Class Recording Slide Presentation, and an Online Course Page on Our Website. The Six-Step Pipeline and My Two-Level Review Process Are Explained in Detail. Here’s a Template You Can Follow.",
    "date": "2026-07-15",
    "url": "articles/post-class-organizing-loop/"
  },
  {
    "slug": "inspiration-production-system",
    "title": "The Inspiration Production System",
    "summary": "Inspiration can be produced systematically. Build an inspiration pool for content creation: three sources of inspiration (past accumulated content, AI-simulated audiences, and hot topics) plus a tag-retrieval system that turns posts with your personal voice into a system that runs on its own. Coach Jiang shares the hands-on method from two of his classes.",
    "date": "2026-07-13",
    "url": "articles/inspiration-production-system/"
  },
  {
    "slug": "dual-track-planning-loop",
    "title": "Let Two AIs Catch Each Other's Mistakes: My Plan Scored 2/5 From a Mock Review Before I Sent It",
    "summary": "AI writes plans fast, but the catch is that it goes along with you: one model writes and reviews itself and never sees its own blind spots. Using a real government-grant proposal, this article documents the full dual-track mutual-review loop: two AIs from different companies each write the plan independently, catch each other",
    "date": "2026-07-12",
    "url": "articles/dual-track-planning-loop/"
  },
  {
    "slug": "laptop-desktop-webpage-sync-icloud-git",
    "title": "Built a webpage with Codex on your home desktop, then can't find the files to edit on your laptop? The problem is where you stored the project",
    "summary": "Finished a webpage on your desktop, then can",
    "date": "2026-07-11",
    "url": "articles/laptop-desktop-webpage-sync-icloud-git/"
  },
  {
    "slug": "dual-centaur-meeting",
    "title": "Dual-Centaur Meeting: I Bring My Agent, You Bring Your Agent, Four Parties Meet Together",
    "summary": "Complex-project meetings often run two or three hours just to align on goals, yet handing everything to AI agents loses the details. The dual-centaur meeting is the middle path: a person plus their Agent meets another person plus their Agent. Agents filter the data first; people discuss only decisions, trust, and commitment. Includes a five-step workflow and the PAAP, AAP, AA evolution.",
    "date": "2026-07-11",
    "url": "articles/dual-centaur-meeting/"
  },
  {
    "slug": "strong-ai-models-knowledge-workflow-road",
    "title": "The model is the supercar; your knowledge base and workflow are the road beneath it",
    "summary": "Once strong models like Claude Fable and GPT-5.6 Sol arrive, the gaps created by your knowledge base, workflow, rules and acceptance criteria become far more obvious. Three kinds of road walk you through a six-step process for paving the way for AI.",
    "date": "2026-07-10",
    "url": "articles/strong-ai-models-knowledge-workflow-road/"
  },
  {
    "slug": "publish-gate",
    "title": "How to Keep Multiple AIs Editing the Same Website From Clashing",
    "summary": "Maintain a website with AI long enough and version chaos is inevitable: one task edits here, another edits there, and they overwrite each other. Using a real screw-up of my own, this article lays out a three-layer safeguard you can actually set up: workspace isolation, a publish gate, and enforcement, with a ready-to-use public skill package.",
    "date": "2026-07-06",
    "url": "articles/publish-gate/"
  },
  {
    "slug": "loop-engineering-guardrails",
    "title": "Loop Guardrails: Five rules that let AI run on its own without running past the safety limits",
    "summary": "Five guardrails that join Harness Engineering and Loop Engineering: undefended assumptions, three-angle challenge, Non-goals and allowed paths, change-course braking, and grading acceptance evidence. So that when AI works continuously and automatically, a single error doesn",
    "date": "2026-07-06",
    "url": "articles/loop-engineering-guardrails/"
  },
  {
    "slug": "questionnaire-to-slides-agent-workflow",
    "title": "Turn the pre-class questionnaire into a presentation, and then save the process into a skill package",
    "summary": "One class Agent basic teaching demonstration and formal SOP: organize the teaching presentation from the pre-class questionnaire and syllabus, and then condense the steps of making the presentation into the Agent workflow, lecture-prep skill package and knowledge base. Suitable for AI novices, lecturers and consultants to read first.",
    "date": "2026-07-06",
    "url": "articles/questionnaire-to-slides-agent-workflow/"
  },
  {
    "slug": "map-is-not-the-territory",
    "title": "The Map Is Not the Territory",
    "summary": "When working with AI, what really gets you stuck is often that the map you hand over is too simple, and no matter how powerful the model, it can",
    "date": "2026-07-05",
    "url": "articles/map-is-not-the-territory/"
  },
  {
    "slug": "ai-changed-behavior-into-workflow",
    "title": "Catch the Behavior AI Quietly Changed, and Turn It Into a Workflow",
    "summary": "On a business trip, I noticed my first move for planning a route had shifted from opening the map to asking AI. Starting from that case, this piece teaches you to spot these quietly AI-changed behaviors, and, following Loop Engineering, turn them into a repeatable workflow in four steps (find the behavior, observe the variables, fix the process, make it a prompt). A copy-paste prompt is included at the end.",
    "date": "2026-07-04",
    "url": "articles/ai-changed-behavior-into-workflow/"
  },
  {
    "slug": "prompt-to-loop-map",
    "title": "From Prompt to Loop Engineering",
    "summary": "Prompt engineering, context engineering, steering engineering, loop engineering. These four stages form one spine that strings together the twenty-odd related articles I have written. Enter at any station and read down.",
    "date": "2026-07-02",
    "url": "articles/prompt-to-loop-map/"
  },
  {
    "slug": "recovery-over-perfection",
    "title": "Instead of Expecting an Error-Free AI System, Design a Fault-Tolerant Loop",
    "summary": "AI will make mistakes, and people give wrong instructions too, so an error-free system is impossible. This piece organizes how I redirect the effort toward fault tolerance: six steps (sort by size, keep an exit, small test first, batch with a trail, verify with a different mind, write a wrap-up note), each with a completion condition and its common pitfall, plus a full worked example.",
    "date": "2026-07-02",
    "url": "articles/recovery-over-perfection/"
  },
  {
    "slug": "harness-mindset-for-bosses",
    "title": "The Boss’s Steering Mindset: Say to AI What You Would Never Say to an Employee",
    "summary": "Many bosses think using AI means learning a pile of new tools. But it is the Agent era now: AI can already work as an employee, and you can be ten times harder on it. This covers the steering mindset, with the ten steering questions, inward questioning, and a good-boss comparison, all copy-paste.",
    "date": "2026-07-02",
    "url": "articles/harness-mindset-for-bosses/"
  },
  {
    "slug": "ai-loop-safety-recovery",
    "title": "AI Errors Aren't the Danger, Having No Backup Is: Lessons From Corrupting 170 Files",
    "summary": "A fully autonomous rename task corrupted 170 files, and the AI still reported",
    "date": "2026-07-01",
    "url": "articles/ai-loop-safety-recovery/"
  },
  {
    "slug": "ai-delegators-optimism",
    "title": "The more you hand work to AI, the more you want it stronger, and the less you fear replacement",
    "summary": "From Anthropic",
    "date": "2026-07-01",
    "url": "articles/ai-delegators-optimism/"
  },
  {
    "slug": "tag-wiki-method",
    "title": "Turn Tags Into Cards, and Your Knowledge Base Comes Alive: The Tag Wiki Method",
    "summary": "Upgrade a tag from a keyword you stick on to a card with real content. Controlled across four dimensions, almost no YAML, and a clear account of how this method complements dense interlinking and RAG rather than replacing them.",
    "date": "2026-07-01",
    "url": "articles/tag-wiki-method/"
  },
  {
    "slug": "give-ai-choices-not-descriptions",
    "title": "Give AI Choices, Not Descriptions: Six Color Palettes at Once, Then Fine-Tune",
    "summary": "The slowest part of working with AI on styles is the endless back-and-forth guessing. Change your prompt: ask for six palettes side by side, pick the one you like, fine-tune on the spot, and copy the final CSS in one click. Three steps, no repeated descriptions. Includes a live demo.",
    "date": "2026-06-30",
    "url": "articles/give-ai-choices-not-descriptions/"
  },
  {
    "slug": "company-shape-is-the-moat",
    "title": "The Real Moat in the AI Era: Organizational Shape, Shared Consensus, Influence, and User Trust",
    "summary": "In the AI era, products, technology, and categories are all being replicated at speed. Investor Jaya Gupta argues the moat is the shape a company grows into. Here I synthesize her argument and add a more concrete take: organizational patterns are like skeletons that can be copied. What truly cannot be taken is consensus, influence, and user trust, things that only accumulate over time.",
    "date": "2026-06-30",
    "url": "articles/company-shape-is-the-moat/"
  },
  {
    "slug": "four-lens-rapid-review",
    "title": "When Busy Becomes Directionless: A Four-Lens Rapid Review",
    "summary": "Running multiple projects at once, staying busy but losing clarity? This six-step rapid review (spread the facts, feedback-leverage matrix, four-lens audit, externalization filter, converge to one action) helps you recalibrate. Runs on a single sheet of paper.",
    "date": "2026-06-30",
    "url": "articles/four-lens-rapid-review/"
  },
  {
    "slug": "my-three-loops",
    "title": "When I Started Thinking in Loops: Three Workflows Redesigned as Loops",
    "summary": "From writing prompts to designing loops. I took three workflows I was already running and turned them into three named loops: a publishing loop (outward), a tacit-knowledge distillation loop (inward), and a retrospective loop (backward), all orbiting the same knowledge base.",
    "date": "2026-06-30",
    "url": "articles/my-three-loops/"
  },
  {
    "slug": "market-to-ai",
    "title": "Two Things You Can Learn Right Now: Using AI for Marketing, and Marketing to AI",
    "summary": "When AI starts making decisions on people",
    "date": "2026-06-29",
    "url": "articles/market-to-ai/"
  },
  {
    "slug": "a2a-agent-protocol",
    "title": "AI Agents Are Taking Over Your Workflows. Are Your Processes and Knowledge Ready?",
    "summary": "As AI agents begin delegating tasks to each other, the real bottleneck is not technology. It is whether your organization",
    "date": "2026-06-28",
    "url": "articles/a2a-agent-protocol/"
  },
  {
    "slug": "intangible-assets-grow-by-sharing",
    "title": "Intangible Assets Grow by Sharing",
    "summary": "Intangible assets grow the more you share them. In the AI era, experience, thinking, and judgment can be amplified by AI into knowledge capital. From content creation to a digital chamber of commerce, sharing my path to becoming an intangible capitalist.",
    "date": "2026-06-28",
    "url": "articles/intangible-assets-grow-by-sharing/"
  },
  {
    "slug": "intent-first-prompting",
    "title": "Stop Writing Rigid Instructions: Say What You Want, Let AI Handle the Rest",
    "summary": "In 2024 everyone rushed to learn prompts. The game has changed. AI is now smart enough to think of better approaches than you, and locking it into rigid instructions wastes that. This is the core mindset of steering engineering: intent first, with three copy-paste prompts.",
    "date": "2026-06-27",
    "url": "articles/intent-first-prompting/"
  },
  {
    "slug": "parenting-story-ai-family-dialogue",
    "title": "Use AI to turn parent-child daily life into stories, illustrations and family conversation materials",
    "summary": "Complete record of the parent-child storytelling AI workshop: the guidance method of the Red Tomato Agreement, script and illustration prompts, live-action movie poster techniques, five finished products from a parent-child story, and finally back to family dialogue.",
    "date": "2026-06-27",
    "url": "articles/parenting-story-ai-family-dialogue/"
  },
  {
    "slug": "what-is-loop-engineering",
    "title": "What Is Loop Engineering? Explained Through My Article-Writing Workflow",
    "summary": "What is loop engineering? No code required. Coach Jiang explains the concept through his article-writing workflow: the difference between prompts and loops, the five phases of a loop, the minimum required components, and when it is actually worth building one.",
    "date": "2026-06-27",
    "url": "articles/what-is-loop-engineering/"
  },
  {
    "slug": "tidy-mess-before-consulting",
    "title": "Tidy the Mess Before Consulting: Let AI Turn Chaos into a Question",
    "summary": "Can",
    "date": "2026-06-26",
    "url": "articles/tidy-mess-before-consulting/"
  },
  {
    "slug": "ai-capability-tiers",
    "title": "Where Do You Stand in the AI World? A 14-Tier Capability Ranking by Industry Impact",
    "summary": "Coach Jiang",
    "date": "2026-06-26",
    "url": "articles/ai-capability-tiers/"
  },
  {
    "slug": "vibe-coding-ten-half-products",
    "title": "You Think You Are Building One Product. You Are Actually Raising Ten Half-Finished Ones.",
    "summary": "A short interview video uses an addiction metaphor to trace one person",
    "date": "2026-06-26",
    "url": "articles/vibe-coding-ten-half-products/"
  },
  {
    "slug": "docs-as-system-design-agent",
    "title": "Docs as System Design: How Non-Engineers Build Agent Frameworks",
    "summary": "You don",
    "date": "2026-06-25",
    "url": "articles/docs-as-system-design-agent/"
  },
  {
    "slug": "how-ai-connects-software",
    "title": "How AI Agents Connect to Software Directly",
    "summary": "Today",
    "date": "2026-06-24",
    "url": "articles/how-ai-connects-software/"
  },
  {
    "slug": "decision-ladder-non-programmer",
    "title": "Ponytail: The \"Decision Ladder\" for People Who Don't Write Code",
    "summary": "Ponytail started as an engineering skill for trimming AI-generated over-engineered code. What it actually solves is universal: AI that says too much. This article moves the decision ladder from code to writing, organizing, and training AI employees, and explains the key that makes it work: burden reversal.",
    "date": "2026-06-24",
    "url": "articles/decision-ladder-non-programmer/"
  },
  {
    "slug": "codex-log-health-check",
    "title": "Codex Crashed? Check logs_2.sqlite First After Reinstalling",
    "summary": "When Codex Desktop won",
    "date": "2026-06-23",
    "url": "articles/codex-log-health-check/"
  },
  {
    "slug": "meeting-record-agent-workflow",
    "title": "My Meeting-Record Agent Workflow",
    "summary": "Starting from in-person recording, OBS online screen capture, and MacWhisper or VibeVoice-ASR transcription, then step by step adding on-the-ground observations, preserving the raw material, generating a meeting strategy report and first-draft deliverables, and finally using multiple thinking models to check for blind spots.",
    "date": "2026-06-23",
    "url": "articles/meeting-record-agent-workflow/"
  },
  {
    "slug": "line-group-ai-workflow",
    "title": "How to Auto-Archive Data Scattered Across LINE Groups Every Day",
    "summary": "A one-page guide to automatically downloading messages, images, PDFs, and files scattered across LINE groups via an official account, organizing them into folders by group, and handing the results to an Agent.",
    "date": "2026-06-22",
    "url": "articles/line-group-ai-workflow/"
  },
  {
    "slug": "elon-musk-live-skill",
    "title": "The Live Elon Musk Skill",
    "summary": "A deep-dive introduction to the Live Elon Musk Skill. It distills Elon Musk",
    "date": "2026-06-22",
    "url": "articles/elon-musk-live-skill/"
  },
  {
    "slug": "how-to-train-your-ai-employee",
    "title": "Build Your AI Employees + Consultants",
    "summary": "Teaching slides from a hands-on workshop: set up AI as your employee to work the way you do, then add a panel of consultants to challenge your blind spots. Covers org structure, the seven-layer tacit knowledge distillation system, connecting nodes into workflows, and how to judge what a problem is worth.",
    "date": "2026-06-21",
    "url": "articles/how-to-train-your-ai-employee/"
  },
  {
    "slug": "ai-market-microcosm",
    "title": "AI Is a Microcosm of the Entire Market",
    "summary": "Market research is slow and costly, but AI has been trained on vast amounts of real human writing and is itself a microcosm of the market. Research by Colgate and PyMC Labs confirms that asking AI to write reactions first and then convert them into scores can simulate purchase intent to within 90% of human self-consistency. Includes a copy-paste prompt and a free skill package.",
    "date": "2026-06-20",
    "url": "articles/ai-market-microcosm/"
  },
  {
    "slug": "own-ai-team-at-work",
    "title": "You Can Have Your Own AI Team Even as a Company Employee",
    "summary": "You can choose to see yourself as an employee, or as the owner of a company of one with your employer as your only long-term client. Same job, different mindset. And without that shift, you will never build your own AI team.",
    "date": "2026-06-20",
    "url": "articles/own-ai-team-at-work/"
  },
  {
    "slug": "knowledge-base-three-vault-split",
    "title": "My Knowledge Base Got Too Big, So I Split It Three Ways",
    "summary": "When a knowledge base grows too large to navigate, ask one question: who actually uses this? That single question splits everything into three vaults (main, secondary, and public-facing) with a simple filing workflow and one clear exception.",
    "date": "2026-06-19",
    "url": "articles/knowledge-base-three-vault-split/"
  },
  {
    "slug": "ai-king-off-battlefield",
    "title": "The AI King Stays Off the Battlefield",
    "summary": "This is not a prediction, and I have no inside information. I want to offer a different lens for reading AI trends: stop fixating on benchmark scores. As models become increasingly commoditized, what may truly be scarce is the access point. Apple and Google, often criticized for weaker models, may be the ones dispatching orders from behind the throne.",
    "date": "2026-06-17",
    "url": "articles/ai-king-off-battlefield/"
  },
  {
    "slug": "codex-only-auto-worklog",
    "title": "Building Your Own Automatic Work Log with Codex Alone",
    "summary": "Many people lose track of their work context soon after they start using AI agents. This article offers two paths: if you only use Codex, its built-in automation is all you need; if you use multiple agents, you need a cross-agent work mirror. Includes three copy-ready Codex work log prompts.",
    "date": "2026-06-16",
    "url": "articles/codex-only-auto-worklog/"
  },
  {
    "slug": "agent-workflow-builds-automation",
    "title": "I Used an Agent to Build My Automated Workflow",
    "summary": "Automation is best understood as two distinct concepts: an Agent workflow builds the process for you, while a programmatic automation workflow runs it on its own. Using a Codex-powered LINE backup bot as a case study, this article breaks down how the two work together and gives you a practical framework for deciding what to hand off to AI and what to hand off to code.",
    "date": "2026-06-16",
    "url": "articles/agent-workflow-builds-automation/"
  },
  {
    "slug": "youtube-to-opinion-report-workflow",
    "title": "A complete workflow for turning a YouTube video into an opinion report webpage",
    "summary": "A complete demonstration of turning YouTube videos into opinion report webpages: NotebookLM conversion to verbatim drafts, desktop Agent local organization, design skill package layout, plus the way of thinking about task submission, acceptance, and accumulation of skill packages.",
    "date": "2026-06-14",
    "url": "articles/youtube-to-opinion-report-workflow/"
  },
  {
    "slug": "caught-ai-slacking-into-rules",
    "title": "I Caught My AI Slacking, Then Wrote It Into the Rules",
    "summary": "I asked Codex to call Claude to revise an article. It never actually called Claude, yet returned what looked like a finished result. This is the retrospective: how to verify whether an AI truly executed an external action, and how to turn each failure into a rule that gets enforced next time.",
    "date": "2026-06-08",
    "url": "articles/caught-ai-slacking-into-rules/"
  },
  {
    "slug": "yongli-ai-workshop-tools-to-workflow",
    "title": "Chamber of Commerce One-Day AI Workshop: From Tool Understanding to Workflow and Knowledge Base",
    "summary": "A full record of a one-day AI workshop for a chamber of commerce: from dismantling tool anxiety and understanding AI",
    "date": "2026-05-30",
    "url": "articles/yongli-ai-workshop-tools-to-workflow/"
  },
  {
    "slug": "diary-driven-agent-3x4",
    "title": "Write a Diary, Put AI to Work",
    "summary": "You don",
    "date": "2026-05-28",
    "url": "articles/diary-driven-agent-3x4/"
  },
  {
    "slug": "teacher-prep-knowledge-workflow",
    "title": "How lecturers use knowledge management processes to turn lesson preparation into a reusable system",
    "summary": "An Agent lesson-prep workflow for lecturers, consultants and knowledge workers: from finding information, an inspiration pool, pre-class questionnaires, promotion, lesson prep and deliverables, to post-class repurposing and cross-course reuse.",
    "date": "2026-05-23",
    "url": "articles/teacher-prep-knowledge-workflow/"
  },
  {
    "slug": "relationship-boundary-ai-practice",
    "title": "Use AI to practice subject separation, return of responsibility and emotional response",
    "summary": "A full write-up of the Relationship Without Internal Friction Practice Course: guidance methods for subject separation and returning responsibility, two AI practice modes (cold analysis and hot companionship), perspective translation and handling resistance, and the all-important red line list. AI is a practice ground, not psychotherapy.",
    "date": "2026-05-20",
    "url": "articles/relationship-boundary-ai-practice/"
  },
  {
    "slug": "web-chat-ai-vs-desktop-agent",
    "title": "Web-based chat AI vs. desktop work AI: Codex is a GPT desktop version installed on your computer",
    "summary": "A beginner-friendly guide to the boundaries between chat AI, single-purpose web tools, and desktop agents: three pain points of project mode, the paradigm shift of the desktop era, Codex, and a three-layer division-of-labor workflow. Liberal arts folks can pick it up without writing code.",
    "date": "2026-05-11",
    "url": "articles/web-chat-ai-vs-desktop-agent/"
  },
  {
    "slug": "books-videos-pdf-ai-advisor",
    "title": "Convert books, videos, and PDFs into conversational AI consultants",
    "summary": "A complete method for turning external materials into an AI consultant that can be questioned: sorting out sources, extracting thinking framework, writing consultant settings, and verifying compatibility. Take the real-life case of turning Naval’s books and interviews into digital clones.",
    "date": "2026-05-03",
    "url": "articles/books-videos-pdf-ai-advisor/"
  },
  {
    "slug": "liberal-arts-agent-framework",
    "title": "Liberal arts majors can hand their work to AI without writing code: designing your own Agent framework",
    "summary": "A general-education course on Agent framework design for non-coders: the three parts of Harness Engineering, Loop Engineering and three kinds of journals, the LLM Wiki knowledge graph and the Tag Wiki tag system. You can hand your work to AI without writing code.",
    "date": "2026-04-20",
    "url": "articles/liberal-arts-agent-framework/"
  },
  {
    "slug": "ai-learning-map-reduce-anxiety",
    "title": "Use AI to build a trackable learning map to reduce information anxiety",
    "summary": "Bookmarks folder full of things saved for later? Use an Agent to organize learning materials scattered everywhere into one visible learning map: skill tree, learning record, personal profile. A three-layer structure with teacher lesson-plan and scheduling-system cases.",
    "date": "2026-03-29",
    "url": "articles/ai-learning-map-reduce-anxiety/"
  },
  {
    "slug": "ai-course-map-from-entry-to-workflow",
    "title": "From entry to workflow: Coach Jiang’s AI course map",
    "summary": "A vertically structured AI course map: an Agent onboarding foundation at the center, applying ready-made workflows going up, and three deep-dive lines going down (data organization, tacit knowledge distillation, and semantic engineering). It all converges on an Agent-powered solo-company operations team.",
    "date": "2026-03-20",
    "url": "articles/ai-course-map-from-entry-to-workflow/"
  },
  {
    "slug": "ai-data-organization-usable-system",
    "title": "How to organize data in the AI era and turn files into usable systems",
    "summary": "The complete method from my AI-era data organization foundations class: use four Markdown syntaxes, carding, linking, and controlled vocabulary to turn your files into a system both people and AI can use, with copy-paste prompts included.",
    "date": "2026-03-09",
    "url": "articles/ai-data-organization-usable-system/"
  },
  {
    "slug": "claude-skills-knowledge-assets",
    "title": "What Are Claude Skills? Turn Your Professional Workflow into a Knowledge Asset AI Can Run Again and Again",
    "summary": "Understand skill packages through Claude Skills: a skill package is an operation manual written for AI that packages your professional workflow, format standards, and best state into a knowledge asset that can be run repeatedly. Includes two ways to build one, plus backup tips.",
    "date": "2026-02-28",
    "url": "articles/claude-skills-knowledge-assets/"
  },
  {
    "slug": "semantic-rules-before-prompt-templates",
    "title": "Why Are Prompt Templates Hit-or-Miss? First Understand That AI Is a Phone Keyboard, 100 Million Times More Powerful",
    "summary": "The underlying logic of prompt design: AI is a word-association calculator, like a phone keyboard 100 million times more powerful. From the three-step fix for task separation and the limits of role-setting to the trap of negative prompts, understand the semantics before you reach for a template.",
    "date": "2026-01-24",
    "url": "articles/semantic-rules-before-prompt-templates/"
  },
  {
    "slug": "notebooklm-knowledge-analysis-assistant",
    "title": "How NotebookLM Goes from a Data-Organizing Tool to a Knowledge-Analysis Assistant",
    "summary": "A full guide to NotebookLM: evolving from having AI summarize for you to having the report read you. Personal profiles, multi-source knowledge bases, a real cross-field syllabus collaboration case, plus two organizing tips — the PDF trap and Markdown content boundaries.",
    "date": "2026-01-04",
    "url": "articles/notebooklm-knowledge-analysis-assistant/"
  },
  {
    "slug": "ai-mvp-validation-before-product",
    "title": "Validate Your Startup Idea with AI Before Spending Big on a Product",
    "summary": "Customers say it",
    "date": "2025-09-10",
    "url": "articles/ai-mvp-validation-before-product/"
  }
];
