/* 站內搜尋別名庫（2026-08-07 建）
   每篇文章掛「訪客會怎麼搜」的口語別名，search.js 與 articles-render.js 會把它併進比對範圍。
   維護：新文章上稿時補一條；訪客搜尋 log 發現沒接住的問法，第一線修法＝來這裡補別名。
   key＝articles-data.js 的文章 id。 */
window.SEARCH_ALIASES = {
  "long-answer-three-layers": ["AI回答太長", "看不下去", "AI講太複雜", "請AI用白話", "白話重講", "叫AI畫流程圖", "Mermaid流程圖", "show_widget", "做成互動網頁", "好好都可以", "AI回答看不懂", "長回答怎麼看"],
  "session-messaging-reminder-layer": ["對話之間傳訊息","Claude Code多視窗","開好幾個AI視窗","AI視窗互相不知道","交接指令複製貼上","session傳訊息","兩個AI改同一個檔案","桌機筆電AI不通","Claude跟Codex不通","多視窗協作怎麼防撞"],
  "messaging-apps-ai-friendliness": ["通訊軟體選哪個","LINE跟Discord比較","AI放哪個群組","聊天軟體AI整合","Slack Agent","Telegram bot","群組軟體AI友善","哪個通訊軟體適合AI助教"],
  "free-deploy-three-boundaries": ["免費網頁部署","網站放哪裡","GitHub Pages還是Vercel","網頁權限保護","架站要花錢嗎","私密網頁怎麼做","免費架站平台","網站被爬蟲讀"],
  "ten-year-anchor": ["AI焦慮怎麼辦","學不完AI怎麼辦","追不上AI新聞","找自己的天賦","定位迷茫","資訊焦慮解法","一直在追新工具","AI學了很多卻講不出重點"],
  "teach-ai-not-learn-ai": ["AI老是重講一遍","AI記不住我的需求","怎麼教AI","AI學不會我的習慣","新人上工說明","帶人心法用在AI","資料庫知識庫規則庫差別","覺得還沒學會AI不敢開始"],
  "timing-and-forecast": ["題目時機怎麼抓","太早講沒人懂","市場太擠","課程題目怎麼選","趨勢跑多快","兩年時間落差","顧問選題時機","痛點反推"],
  "ai-native-not-transformation": ["公司AI導入沒用","推不動AI","老闆不敢放權","AI只是快一點","為什麼員工裝死","企業數位轉型卡關","AI導入沒效果原因","工具買了課也上了沒用"],
  "agent-workflow-builds-automation": ["AI自動化跟程式自動化差在哪","Agent怎麼分工","LINE備份機器人","用Codex設定自動化","重複工作變自動流程","AI該插手在哪一段"],
  "codex-only-auto-worklog": ["工作日誌自動記錄","忘記今天做了什麼","Codex定時任務","跨Agent工作鏡子","自動寫工作紀錄","工作痕跡很散"],
  "program-vs-ai-skill-library": ["AI導入企業卡在哪","ERP還是AI","技能庫怎麼建","企業AI用在哪","不知道AI用在哪","確定跟不確定的工作怎麼分"],
  "spacex-ipo-musk-trillionaire-knowledge-work": ["馬斯克上市","知識工作者還剩什麼價值","執行被自動化","工作被AI取代焦慮","SpaceX招股書","一兆美金"],
  "demis-hassabis-agi-science-ai": ["AGI是什麼","後稀缺時代","Google DeepMind執行長","知識管理長期趨勢","AI員工佈局","智能與意識分離"],
  "apple-wwdc26-siri-lobster-ai": ["蘋果WWDC","Siri進化","Apple Intelligence","App Intents","助理會自己動手","Xcode agents","龍蝦AI是什麼"],
  "caught-ai-slacking-into-rules": ["AI假裝完成任務","AI沒做卻說做了","怎麼確認AI真的執行","AI打混摸魚","多模型分工出包","AI回答看起來完成其實沒做"],
  "ai-king-off-battlefield": ["蘋果Google入口之爭","模型跑分排行榜","AI產業結構視角","誰掌握入口","追AI新聞只看跑分","王者不上戰場","後台的王"],
  "knowledge-base-three-vault-split": ["知識庫太亂","筆記越存越多找不到","Obsidian庫太大","知識庫怎麼拆","主庫副庫對外庫","找文件要捲很久"],
  "own-ai-team-at-work": ["上班族用AI","打工仔AI團隊","員工心態換老闆心態","副業接案訓練AI","在公司多做也沒用","中高階主管AI","資深工作者副業"],
  "ai-market-microcosm": ["市場調查太貴","產品沒人買怎麼辦","landing page被誤解","用AI模擬顧客反應","新產品驗證意願","測反應省市調錢"],
  "how-to-train-your-ai-employee": ["怎麼訓練AI員工","AI員工怎麼帶","隱性知識提煉七層","工作坊教學簡報","問題值多少錢","習慣自己動手不敢交出去"],
  "line-group-ai-workflow": ["聊天群組檔案找不到", "LINE群組資料整理","群組訊息備份","官方帳號自動下載","LINE圖片PDF歸檔","Mika助教","群組資料過幾天找不回來","群組檔案找不到","聊天記錄找不到"],
  "elon-musk-live-skill": ["第一性原理顧問","馬斯克思考方式","拆問題盲點","開源技能包下載","創業者顧問AI","反問假設"],
  "codex-log-health-check": ["Codex打不開","Codex Desktop當機","Codex重灌","logs_2.sqlite","Codex任務不見了","Codex更新無效"],
  "how-ai-connects-software": ["API CLI MCP是什麼","AI怎麼連軟體","AI操作電腦","AI操作網頁","USB比喻MCP","AI Agent直接操作軟體"],
  "meeting-record-agent-workflow": ["會議整理流程","逐字稿轉錄","MacWhisper","VibeVoice","會議策略書","開會錄音整理","會議缺待辦風險決策"],
  "decision-ladder-non-programmer": ["AI廢話太多","AI講太發散","簡潔一點沒用","工程師技能包搬過來","舉證反轉","Ponytail決策階梯"],
  "ai-capability-tiers": ["我在AI世界哪個位置","T0到T13","AI能力分級","團隊誰適合做AI工作","對照自己在AI領域位置","下一步該往哪走","十四層能力表"],
  "docs-as-system-design-agent": ["不會寫程式設計Agent","非工程師做AI角色","人格思維提煉","多Agent系統","文件就是系統怎麼理解","設計Agent是工程師的事嗎","會帶人會設計流程"],
  "vibe-coding-ten-half-products": ["vibe coding","專案做一半收不了尾","AI寫程式養一堆爛尾","第一性原理收斂專案","什麼都想用AI做結果做不完","訪談短片AI顧問收斂","八個專案篩成三個"],
  "tidy-mess-before-consulting": ["講不清楚問題","ChatGPT專案資料夾","找人討論卡住","混亂整理成問題","找顧問前先整理","自己卡在哪講不清楚","先整理好再來","筆記一團亂","東西很亂不知道從哪開始"],
  "diary-driven-agent-3x4": ["寫日記給AI用","三種日記四種時效","建知識庫不知道怎麼開始","散亂資料整理","3X4資料整理法","不用寫程式建知識庫","任何一家AI都讀得懂"],
  "what-is-loop-engineering": ["Loop Engineering是什麼","不要只寫提示詞","一步一步叫AI很累","迴圈五個階段","迴圈工程入門","寫一篇文章的工作流","最少零件"],
  "intangible-assets-grow-by-sharing": ["經驗換不成錢","知識資本","自媒體到數位商會","無形資本家","分享會不會被學走","一顆蘋果一個微笑","前進階梯"],
  "a2a-agent-protocol": ["A2A協議","代理互相交辦工作","組織流程機器讀得懂","名片示範","AI代理協作準備","流程和知識準備好了嗎","拆解任務劃清資料邊界"],
  "market-to-ai": ["學行銷從哪開始","對AI做行銷","讓AI幫你決定要買什麼","行銷新手時間怎麼分配","用AI行銷跟對AI行銷差在哪","名片自測","四步開始學行銷"],
  "agent-web-turning-point": ["機器人流量超過真人","內容被AI讀","AXO是什麼","網站準備被AI引用","十分鐘自測","訪問已經不是人了"],
  "four-lens-rapid-review": ["忙到迷惘","抓不到重點","快速復盤法","六步復盤","一張紙復盤","同時開好幾條線"],
  "give-ai-choices-not-descriptions": ["跟AI調配色","AI一直猜不對","網頁樣式來回試","ai-web-tuner","配色校稿器","調樣式很慢很燒額度"],
  "my-three-loops": ["不會寫程式也能設計流程","提示詞跟規則差在哪","三條loop案例","每次都要重新交代一遍","今天就能做的第一步","會寫規則就能讓AI照做"],
  "company-shape-is-the-moat": ["護城河是什麼","組織模式抄不走","共識影響力信任","創投觀點AI時代","技術容易被複製","模型產品技術被快速複製","時間長出來的累積"],
  "tag-wiki-method": ["標籤亂增生","存了等於沒存","受控詞彙","標籤變卡片","RAG跟標籤差在哪","Tag Wiki標籤連結法"],
  "ai-loop-safety-recovery": ["AI自動跑批次出錯","檔案被改壞","獨立複驗","跨家驗證","備援機制","170個檔案打壞"],
  "recovery-over-perfection": ["AI出錯怎麼辦","容錯設計六步","批次改名示範","出錯後標準動作","300份檔案改名","分大小留後路先小試","設計不會犯錯的系統不可能"],
  "intent-first-prompting": ["提示詞越寫越長沒用","指令寫死綁住AI","意圖優先提示詞","上下文駕馭迴圈差在哪","AI發揮不出來","為什麼做做到什麼程度","四個名詞賽馬圖解"],
  "harness-mindset-for-bosses": ["老闆學AI很痛苦","對AI比對員工狠","駕馭十問","管理經驗用在AI上","AI產出只是看起來還行","帶了幾十年員工","AI讓你做得快判斷更值錢"],
  "prompt-to-loop-map": ["文章讀不出全貌","四階段知識地圖","從頭開始讀哪一篇","AI協作總覽","20篇文章順序","越往下越不用管AI怎麼做","系統地讀完AI協作文章"],
  "ai-delegators-optimism": ["會不會被AI取代","Anthropic報告","任務分三層","把流程做成技能包","AI越強越怕失業","Cadences報告五張圖表","越把工作交給AI越樂觀"],
  "ai-changed-behavior-into-workflow": ["不知不覺被AI改變習慣","查行程問AI","固定成流程","迴圈工程四步實例","習慣沒有固定成流程","出差查行程","打開地圖變成問AI"],
  "map-is-not-the-territory": ["AI一直猜錯","要你重講一遍","四種未知","Anthropic工程師Thariq","動手前先畫地圖","判斷交給AI講不清楚"],
  "questionnaire-to-slides-agent-workflow": ["問卷做簡報","lecture-prep技能包","Agent基礎教學新手","備課流程沉澱","課前問卷變簡報","Agent新手必讀","從資料蒐集到成品"],
  "teacher-prep-knowledge-workflow": ["備課從零開始","八階段知識管理流程","課後資料沒回流","靈感池","講師知識管理","找資料靈感池課前問卷","讓每次上課餵養下一次"],
  "publish-gate": ["多個AI改同一個網站打架","版本錯亂","部署後連結壞了","git worktree","pre-push hook","publish-gate技能包"],
  "yongli-ai-workshop-tools-to-workflow": ["企業AI課程","商會工作坊","中小企業主AI導入","NotebookLM桌面型Agent","一日AI工作坊","課程停在工具展示"],
  "youtube-to-opinion-report-workflow": ["影片變報告","YouTube逐字稿工作流","NotebookLM轉逐字稿","桌面型Agent示範","影片看完難沉澱","交任務驗收沉澱技能包","一支影片變網頁","影片心得","看完影片整理心得","YouTube 筆記"],
  "loop-engineering-guardrails": ["AI自動連跑安全範圍","未抗辯假設","三視角抗辯","換路煞車","驗收證據分級","迴圈護欄五條規則"],
  "parenting-story-ai-family-dialogue": ["親子AI創作","說故事工作坊","插畫提示詞","家庭對話素材","紅番茄協議","親子日常變故事"],
  "ai-mvp-validation-before-product": ["創業點子驗證","客戶說很棒卻不買","VJPD框架","承諾訊號評分","MVP前期驗證","花大錢做產品前"],
  "books-videos-pdf-ai-advisor": ["把書變成AI顧問","數位分身怎麼做","萃取思維框架","Naval案例","書影片PDF轉對話","整理來源驗證契合度","AI顧問人格技能包"],
  "liberal-arts-agent-framework": ["不會寫程式也能做Agent","文科生學AI","駕馭工程三件事","LLM Wiki知識圖譜","文科生設計框架","Agent框架只能從工程語法學嗎","通識課設計自己的Agent"],
  "ai-learning-map-reduce-anxiety": ["收藏夾存了一堆沒看","學AI不知道下一步","技能樹","學習履歷","個人設定檔","資訊焦慮學習地圖"],
  "relationship-boundary-ai-practice": ["用AI練習溝通","關係內耗","課題分離","責任歸還","情緒回應練習","AI不是心理治療"],
  "web-chat-ai-vs-desktop-agent": ["Codex是什麼","聊天型AI跟桌面型差在哪","GPT桌面版","新手分不清AI工具","所有AI都當聊天框","三個痛點範式轉變","文科生不用寫程式"],
  "ai-course-map-from-entry-to-workflow": ["江江教練課程系統","AI課程怎麼選","課程路線圖","一人公司營運團隊終點","課程地圖","地基層Agent導入","垂直結構課程系統"],
  "ai-data-organization-usable-system": ["文件變系統","Markdown整理資料","卡片化教學","受控詞彙基礎班","文件找不到接不上工作流","人和AI都能用的系統","四個語法連結與受控詞彙"],
  "semantic-rules-before-prompt-templates": ["提示詞模板為什麼失效","手機輸入法比喻","角色設定限制","負向提示詞陷阱","模板時好時壞","先懂語意再套模板","課題分離三步修正"],
  "claude-skills-knowledge-assets": ["技能包是什麼","Claude Skills入門","流程變知識資產","技能包怎麼做","技能包備份","操作手冊給AI看","AI 記不住","換對話就忘記","讓 AI 一直記得我的做法"],
  "notebooklm-knowledge-analysis-assistant": ["NotebookLM怎麼用","讓報告來讀你","個人檔案設定","PDF陷阱","多來源知識庫","資料整理工具變分析助理"],
  "strong-ai-models-knowledge-workflow-road": ["模型越來越強沒感覺","換了引擎原地打滑","知識庫工作流投資","六步AI鋪路流程","Claude Fable GPT-5.6","泥巴路柏油路高速公路","同樣的AI別人用起來像換引擎"],
  "dual-track-planning-loop": ["企劃被模擬評審打分","雙軌互審","AI寫自己審看不到盲點","政府補助提案案例","兩個AI互相挑錯","對家終審決策點","被自己想法錨定看不到盲點"],
  "dual-centaur-meeting": ["帶Agent開會","人加AI對人加AI","PAAP AAP AA","複雜專案會議太長","雙人馬會議","中間解Agent先過濾資料","納瓦爾對談時間碼"],
  "laptop-desktop-webpage-sync-icloud-git": ["iCloud跟git衝突","多台電腦做網頁","程式碼放哪裡","換筆電找不到檔案","同步搬家","桌機筆電找不到專案"],
  "inspiration-production-system": ["每天硬想發什麼","靈感池","選題卡住","舊素材找不到","熱門話題選題","沒靈感發文"],
  "post-class-organizing-loop": ["上完課素材散掉","逐字稿三天後就散了","課後六步輸送帶","教學手冊產出","課後整理Loop","兩層審核確保AI整理能用","簡報還是課前骨架版"],
  "ai-handoff-instructions": ["換模型交接","交代太多AI做不完","供應商模式交接","交接單模板","換人續跑","交接指令怎麼寫"],
  "manage-ai-with-management-knowledge": ["豐田TPS用在AI","不懂技術怎麼推AI","管理經驗翻譯成AI規則","自働化停線比喻","覺得要從零學新技術","標準化自働化持續改善","翻成AI流程檢查表"],
  "ai-tools-professional-judgment": ["工具一樣為什麼有差","AI生成程式碼冗長","SlopCodeBench","交付前三問清單","判斷力拉開差距","三名工程師清理AI程式碼收費","看懂問題哪裡不能碰"],
  "ai-cp-value-calculus": ["模型帳單一直漲","該用哪一級模型","最貴模型不一定值得","任務需要幾分","AI的CP值","三張成本對照表","算力有限問題排序"],
  "mika-to-laika-product-character-design": ["同一個助理不同平台能力不同","AI角色拆分","LINE群組助理改名","咪卡萊卡差別","數位角色設計","產品分工再決定視覺","使用者沿用原本理解"],
  "agent-native-tools-software-interface": ["軟體介面會消失嗎","交辦任務不用學操作","找外包團隊比喻","剪片Agent工具","Agent原生工具","每接觸新軟體先學介面","交代任務驗收成果"],
  "knowledge-os-master-map": ["整理法兜不起來","知識體系全貌","八步精煉迴圈","三重收斂信度","知識作業系統母架構","存量三庫八步精煉迴圈","雙AI獨立收斂信度證據"],
  "knowledge-as-employee": ["知識管理分水嶺","AI辦公室能力從哪來","傳統知識管理缺什麼","知識搭配AI工作","把知識當員工","七個面向逐站對照","架構好之後知識自己去工作"],
  "meeting-into-verifiable-loop": ["每週手動重推流程","技能包串起來","喊一聲自己跑完","迴圈邊界說明","會議整理做成迴圈","規則早就寫成技能包","保證什麼不保證什麼"],
  "old-prompts-intent-first-loop-engineering": ["舊提示詞白花時間嗎","隨手一句反而做得好","意圖優先走向迴圈工程","舊技能包不用丟","照著步驟做升級成理解想達成什麼","在意的成果標準慣用思考順序"],
  "chatgpt-work-skills-web-version": ["ChatGPT網頁版技能包","ChatGPT Work上手","專案加技能包","ChatGPT Work兩個雷","網頁版每次要重貼規則","7月12日免費講座","深處一定會撞到的雷點"],
  "chatgpt-work-codex-choice": ["該開哪一個AI","ChatGPT Plus功能怎麼選","Codex裝不了怎麼辦","能力邊界表","Work Codex一般Chat差別","會不會碰本機資料","OpenAI官方文件支持到哪"],
  "personal-studio-vs-solo-company": ["接案跟一人公司差在哪","收入綁工時","專業產品化五步驟","不再用時間換錢","個人工作室升級","馬斯克極端例子系統思維","三套技能包入口"],
  "train-your-ai-agent-editor": ["AI小編訓練","讓AI認識你","問卷變簡報流程","嘉我好漾課程","九段提示詞","AI Agent小編"],
  "why-split-data-into-cards": ["PDF給AI讀不懂","卡片盒筆記法","PPT整理不出來","卡片化拆解教學","原子化提示詞","資料拆成卡片"],
  "ai-that-knows-you": ["數位分身不是長相","複製做事方式","培訓員工比喻","手機十分鐘設定","自我描述提示詞","AI回答總是不夠貼"],
  "one-on-one-questions": ["AI問答集","一對一線上聊","知識庫怎麼建常見問題","公司裡怎麼推AI","職場組織現實","37問"],
  "cli-api-mcp-computer-use": ["CLI API MCP差別","computer use是什麼","GUI比喻","判斷順序MCP優先","叫AI幫你點餐","對人越好用對AI越難用","最慢最燒Token"],
  "rule-file-rebound": ["規則檔越寫越長","精簡後復胖","220條規則盤點","舉證反轉引擎","每週複查行程","規則沒在執行"],
  "answer-to-action-enterprise-ai-agent": ["簡立峰","企業導入AI Agent","六題篩選表","90天學習路線","三層權限護欄","從Answer到Action"],
  "long-task-completion-rate": ["AI跑到一半就停","長流程完工率","Opus 4.8 Fable Opus 5比較","十步驟Loop測試","AI自己跑長流程停在中間","三種卡關反應停住等人","迴圈工程要補的三件事"],
  "talent-vs-expertise": ["找不到自己的強項","天賦怎麼挖","差異提煉法","隨機偶遇法","教練怎麼問出判斷標準","努力學來的專業"],
  "ai-employee-four-levels": ["什麼時候可以放手","駕馭式提問十問","靈魂拷問十問","難度分級放手法","6月7日講座","訓練AI員工四個層次"],
  "use-more-ai-not-enough": ["AI只是變快沒有結構改變","AI原生不是AI優化","Sam Altman訪談","看倍數不看百分比","工作形狀沒有變","過去的軟體做不到的事","20%到50%的加速不算AI強項"]
};
