name = "ai-km-jiang-cf-20261004"
compatibility_date = "2026-09-04"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./.cloudflare-output"

[vars]
CF_SITE_MODE = "preview"

[env.preview.vars]
CF_SITE_MODE = "preview"

[env.production.vars]
CF_SITE_MODE = "production"
CF_PROD_KEYS = "original"
